version: '3'

services:
  db:
    image: mysql/mysql-server
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    container_name: 'mysql02'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: xieguande
      MYSQL_PASSWORD: password
    volumes:
      - /d/docker/beta/mysql/config/my.cnf:/etc/my.cnf
      - /d/docker/beta/mysql/mysql-init:/docker-entrypoint-initdb.d
  web:
    build: .
    container_name: 'aspnetcore'
    ports: 
      - '8003:80'
    depends_on: 
      - db
